name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Build and publish Python distributions
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/nanofetch
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Test and build distributions
        run: |
          python -m pip install --upgrade pip build
          python -m pip install ".[test]"
          python -m pytest
          python -m build

      - name: Publish distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
